"""CAPF protocol constants."""

# Protocol identification
PROTOCOL_ID = 85
PROTOCOL_VERSION = 3

# Commands
COMMAND_AUTH_REQUEST = 1
COMMAND_AUTH_RESPONSE = 2
COMMAND_KEY_GENERATE_REQUEST = 3
COMMAND_KEY_GENERATE_RESPONSE = 4
COMMAND_ENCRYPT_RESPONSE = 5
COMMAND_ENCRYPT_REQUEST = 6
COMMAND_DECRYPT_REQUEST = 7
COMMAND_DECRYPT_RESPONSE = 8
COMMAND_STORE_CERTIFICATE_REQUEST = 9
COMMAND_STORE_CERTIFICATE_RESPONSE = 10
COMMAND_FETCH_CERTIFICATE_REQUEST = 11
COMMAND_FETCH_CERTIFICATE_RESPONSE = 12
COMMAND_DELETE_CERTIFICATE_REQUEST = 13
COMMAND_DELETE_CERTIFICATE_RESPONSE = 14
COMMAND_END_SESSION = 15
COMMAND_RETRY_LATER = 16
COMMAND_REQUEST_IN_PROGRESS = 17
COMMAND_STATUS_REQUEST = 18
COMMAND_STATUS_RESPONSE = 19
COMMAND_ABORT_REQUEST = 20
COMMAND_ABORT_RESPONSE = 21
COMMAND_SIGN_CERTIFICATE_REQUEST = 22
COMMAND_SIGN_CERTIFICATE_RESPONSE = 23

# Elements (TLV tags)
ELEMENT_REASON = 1
ELEMENT_REASON_INFO = 2
ELEMENT_CERTIFICATE_TYPE = 3
ELEMENT_CERTIFICATE = 4
ELEMENT_CERTIFICATE_ID = 5
ELEMENT_SIGNED_DATA = 6
ELEMENT_VERSION = 7
ELEMENT_AUTH_TYPE = 8
ELEMENT_PUBLIC_KEY = 9
ELEMENT_KEY_SIZE = 10
ELEMENT_PASSWORD = 11
ELEMENT_RETRY_DELAY = 12
ELEMENT_DEVICE_NAME = 13
ELEMENT_SUDI_DATA = 16
ELEMENT_KEY_TYPE = 17
ELEMENT_CURVE = 18
ELEMENT_DIGEST_TYPE = 19
ELEMENT_SHA2_SIGNED_DATA = 20

# Reason codes
REASON_NO_ACTION = 0
REASON_UPDATE_CERTIFICATE = 1
REASON_INVALID_ELEMENT = 7
REASON_UNKNOWN_DEVICE = 9

# Authentication types
AUTH_TYPE_NONE = 0
AUTH_TYPE_PASSWORD = 1
AUTH_TYPE_NO_PASSWORD = 2
AUTH_TYPE_LSC = 3
AUTH_TYPE_MIC = 4

# Hash algorithms
HASH_SHA1 = 1
HASH_SHA256 = 2
HASH_SHA512 = 3

# Certificate types
CERTIFICATE_TYPE_LSC = 1
CERTIFICATE_TYPE_MIC = 2

# Key types
KEY_TYPE_RSA = 0
KEY_TYPE_EC = 1

# EC curves
CURVE_SECP256R1 = 0
CURVE_SECP384R1 = 1
CURVE_SECP521R1 = 2

# Curve name to byte mapping
CURVE_NAME_TO_BYTE = {
    "secp256r1": CURVE_SECP256R1,
    "secp384r1": CURVE_SECP384R1,
    "secp521r1": CURVE_SECP521R1,
}

# Valid curve names
VALID_CURVES = frozenset(CURVE_NAME_TO_BYTE.keys())

# Valid RSA key sizes
VALID_KEY_SIZES = frozenset([512, 1024, 2048, 3072, 4096])

# Valid operations
VALID_OPERATIONS = frozenset(["install", "fetch", "delete", "none"])

# Valid authentication modes
VALID_AUTHENTICATIONS = frozenset(["password", "certificate", "no password"])
